import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import Navbar from "./_components/Navbar";
import Search from "./_components/Search";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MantineProvider>
        <body className={`bg-gray-900 text-white min-h-screen`}>
          <div className="flex flex-col min-h-screen md:flex-row h-full">
            <Navbar />
            <main className="flex-1 bg-gray-900 p-6">{children}</main>

            <div className="hidden lg:block">
              <Search />
            </div>
          </div>
        </body>
      </MantineProvider>
    </html>
  );
}
